### ISSUE TITLE
OPA server failing health check

### ISSUE THREAD

**Issue by stobbsm** [CanDIG/CanDIGv2#375]
Noticed that the container image `openpolicyagent/opa:latest-static` is basically an empty container with a static binary, so having a healtcheck based on `curl` will always fail.

Relevant output of docker ps:
```
818cc28fa2aa   openpolicyagent/opa:latest-static   "/opa run --server -…"   19 minutes ago   Up 19 minutes (unhealthy)   0.0.0.0:8181->8181/tcp, :::8181->8181/tcp                       candigv2_opa_1
```

EDIT: Same issue of missing the curl command for vault and minio.

query and candig-data-portal are also failing to get a healthy status, but they do have the curl command. It just fails.

**Comment by stobbsm** [comment]
After looking into it more, I've been able to fix the healthchecks for candig-data-portal and query. The internal server is running on port 3000 it seems, but it was trying to do the healthcheck with the external (host) port.

I'll create a PR to fix this.

**Comment by mshadbolt** [comment]
We think we have fixed this on our develop branch, let us know if it is still an issue
