### ISSUE TITLE
Missing docker-compose installation

### ISSUE THREAD

**Issue by brouillette** [CanDIG/CanDIGv2#73]
Hi guys,

I'm unable to run docker-compose commands after following the docker installation instructions from `docs/install-docker.md`. Was it purposefully omitted, or were we supposed to install it manually?

I'm hesitant to install it manually because I've faced deployment/versioning issues when doing so.

Thanks

**Comment by shaikh-rashid** [comment]
https://github.com/CanDIG/CanDIGv2/commit/5687eae946956febb7adba3a5d56cb027114ffe8#diff-e5bf0c4d65c6ebdd6c6b01258fd727e1ee3f980a26cb203a4676324e35cbc242

**Comment by shaikh-rashid** [comment]
Fixed
