### ISSUE TITLE
Anaconda is not free for comercial use

### ISSUE THREAD

**Issue by stobbsm** [CanDIG/CanDIGv2#741]
Thought you should know, since Candig uses conda, that Anaconda is no longer available under a free license.
I suggest changing the targets to the conda-forge equivalents, as that is still open source. It should be as simple as changing the channels from the default Anaconda channels to the open source conda-forge channels.

I haven't attempted this yet.

**Comment by mshadbolt** [comment]
Thanks for raising this @stobbsm , we are aware of this and have it on our to do list to remove from our stack.

**Comment by mshadbolt** [comment]
We have now updated this in our develop branch with this PR: https://github.com/CanDIG/CanDIGv2/pull/812
